### PR TITLE
Release v0.4.1

### PR DESCRIPTION
**Pull request by caspervdw**
Removes PIMS and pytables as dependencies.

### CODE REVIEW

**Comment by caspervdw** [comment]
@nkeim I also dropped the `pytables` dependency. I am not sure about that, what do you think?

**Comment by nkeim** [comment]
Hmm. I agree that it's one more unnecessary dependency, and getting the right version, etc. should be pandas' problem, not trackpy's. But I think we should take a similar approach to recommending it in the installation instructions. It is approximately as useful as pims.

Do you want to do a "stealth" edit of the docs? Release a special 0.4.1a for conda only? Or just wait until 0.4.2? I think the first option is more than acceptable.

**Comment by jakirkham** [comment]
FYI as this used a branch on the main feedstock, it has already been deployed.

ref: https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

**Comment by nkeim** [comment]
Thanks, @jakirkham !

@caspervdw Sounds like we should just patch the docs. I will do it.

**Comment by caspervdw** [comment]
@jakirkham Sorry about that! I might just as well merge this then

**Comment by jakirkham** [comment]
Would recommend merging since this is already deployed. Can always fork and submit a new PR with a build number bump for other changes (or a new release if you go that way).

**Pull request merged**
